# Generated by Django 6.0.3 on 2026-05-02 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='adress1',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='adress2',
            new_name='address2',
        ),
    ]
